WebPagesAPI/WebPagesParkingSoft/Models/ErrorViewModel.cs
namespace WebPagesParkingSoft.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebPagesAPI/WebPagesParkingSoft/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebPagesParkingSoft.Models;

namespace WebPagesParkingSoft.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebPagesAPI/WebPagesParkingSoft/Controllers/RatesController.cs
using API_AppParkingSoft.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebPagesParkingSoft.Controllers
{
    public class RatesController : Controller
    {
        private readonly IHttpClientFactory _httpClient;
        public RatesController(IHttpClientFactory httpClient) {
            _httpClient = httpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var url = "https://localhost:7211/api/Rates/GetRates";
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            List<Rate> Rates = JsonConvert.DeserializeObject<List<Rate>>(json);

            return View(Rates);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rate Rate)
        {
            var url = "https://localhost:7211/api/Rates/CreateRates";
            await _httpClient.CreateClient().PostAsJsonAsync(url, Rate);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Rates/EditRates/{0}", id);
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            Rate Rate = JsonConvert.DeserializeObject<Rate>(json);
            return View(Rate);
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Rate Rate, Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Rates/EditRates/{0}", id);
            await _httpClient.CreateClient().PutAsJsonAsync(url, Rate);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Rates/GetRates/{0}", id);
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            Rate Rate = JsonConvert.DeserializeObject<Rate>(json);
            return View(Rate);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Rates/GetRates/{0}", id);
            await _httpClient.CreateClient().DeleteAsync(url);
            return RedirectToAction("Index");
        }*/
    }
}

WebPagesAPI/WebPagesParkingSoft/Controllers/ReservesController.cs
using API_AppParkingSoft.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebPagesParkingSoft.Controllers
{
    public class ReservesController : Controller
    {
        private readonly IHttpClientFactory _httpClient;
        public ReservesController(IHttpClientFactory httpClient)
        {
            _httpClient = httpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var url = "https://localhost:7211/api/Reserve/GetActiveVehicles";
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            List<Reserve> reserves = JsonConvert.DeserializeObject<List<Reserve>>(json);

            return View(reserves);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
    }
}

WebPagesAPI/WebPagesParkingSoft/Controllers/VehiclesController.cs
using API_AppParkingSoft.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebPagesParkingSoft.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly IHttpClientFactory _httpClient;
        public VehiclesController(IHttpClientFactory httpClient)
        {
            _httpClient = httpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var url = "https://localhost:7211/api/Vehicles/GetVehicles";
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            List<Vehicle> vehicles = JsonConvert.DeserializeObject<List<Vehicle>>(json);

            return View(vehicles);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Vehicle vehicle)
        {
            var url = "https://localhost:7211/api/Vehicles/CreateVehicles";
            await _httpClient.CreateClient().PostAsJsonAsync(url, vehicle);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Vehicles/EditVehicles/{0}", id);
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            Vehicle vehicle = JsonConvert.DeserializeObject<Vehicle>(json);
            return View(vehicle);
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Vehicle vehicle, Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Vehicles/EditVehicles/{0}", id);
            await _httpClient.CreateClient().PutAsJsonAsync(url, vehicle);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Vehicles/GetVehicles/{0}", id);
            var json = await _httpClient.CreateClient().GetStringAsync(url);
            Vehicle vehicle = JsonConvert.DeserializeObject<Vehicle>(json);
            return View(vehicle);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var url = String.Format("https://localhost:7211/api/Vehicles/GetVehicles/{0}", id);
            await _httpClient.CreateClient().DeleteAsync(url);
            return RedirectToAction("Index");
        }

    }
}

WebPagesAPI/WebPagesParkingSoft/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebPagesAPI/WebPagesParkingSoft/Views/Rates/Delete.cshtml
@model API_AppParkingSoft.DAL.Entities.Rate

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Tarifa</h1>

<h4>Estas seguro que deseas eliminar la tarifa?</h4>
<hr />

a<div class="row">
    <div class="col-12">
        <partial name="../Shared/PartialView/_VehiclesDetailsDelete.cshtml">

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Eliminar" class="btn btn-outline-danger" />
                <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
            </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebPagesAPI/WebPagesParkingSoft/Views/Rates/Index.cshtml
@model IEnumerable<API_AppParkingSoft.DAL.Entities.Rate>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
<a asp-action="CreateRate" class="btn btn-outline-primary">Crear nuevo vehiculo</a>

<div class="row">
    <div class="col-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-primary text-center">Tarifas</h3>
            </div>
        </div>

        <div class="panel-body">
            <table class="table table-hover table-responsive table-striped" id="VehiclesTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.RateName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.hourlyRate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.dailyRate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.weeklyRate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.monthlyRate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.idCategoryVehicle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.RateName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.hourlyRate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.dailyRate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.weeklyRate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.monthlyRate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idCategoryVehicle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Editar</a>
                                @* <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-success">Detalles</a> *@
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

@SectionWriters Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(funtion(){
            $('VehiclesTable').DataTable({
                "languaje": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [5, 25, 50, 100, 200, -1],
                    [5, 25, 50, 100, 200, "Todos"]
                ]
            })
        })
    </script>
 }

WebPagesAPI/WebPagesParkingSoft/Views/Reserves/Index.cshtml
@model IEnumerable<API_AppParkingSoft.DAL.Entities.Reserve>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />

<div class="row">
    <div class="col-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-primary text-center">Reservas Activas</h3>
            </div>
        </div>

        <div class="panel-body">
            <table class="table table-hover table-responsive table-striped" id="ReservasTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.NameUser)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.LicensePlate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.StartDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.activeVehicle)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.NameUser)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LicensePlate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.activeVehicle)
                            </td>
                            @* <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Editar</a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Eliminar</a>
                            </td> *@
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

@SectionWriters Scripts{
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(document).ready(funtion(){
        $('ReservasTable').DataTable({
            "languaje": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            "aLengthMenu": [
                [5, 25, 50, 100, 200, -1],
                [5, 25, 50, 100, 200, "Todos"]
            ]
        })
    })
</script>
 }

WebPagesAPI/WebPagesParkingSoft/Views/Shared/PartialView/_VehiclesCreateEdit.cshtml
@model API_AppParkingSoft.DAL.Entities.Vehicle

<div class="form-group">
    <label asp-for="LicensePlate" class="control-label"></Label>
    <input asp-for="LicensePlate" class="form-control"/>
    <span asp-validation-for="LicensePlate" class="text-danger"></span>
</div>

<div class="form-group">
    <Label asp-for="Brand" class="control-label"></label> 
    <input asp-for="Brand" class="form-control" />
    <span asp-validation-for="Brand" class="text-danger"></span>
</div>

<div class="form-group">
    <Label asp-for="Model" class="control-label"></label> 
    <input asp-for="Model" class="form-control" />
    <span asp-validation-for="Model" class="text-danger"></span>
</div>

WebPagesAPI/WebPagesParkingSoft/Views/Shared/PartialView/_VehiclesDetailsDelete.cshtml
@model API_AppParkingSoft.DAL.Entities.Vehicle

<h4>Vehiculo</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html. DisplayNameFormodel => model.LicensePlate)
    </dt>
    <dd class="col-sm-10">
        @Html. DisplayFor(model => model. LicensePlate)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Brand)
    </dt>
    <dd class="col-sm-10">
        @Html. DisplayFor(model => model.Brand)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Model)
    </dt>
    <dd class="col-sm-10">
        @Html. DisplayFor(model => model.Model)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.CategoryName)
    </dt>
    <dd class="col-sm-10">
        @Html. DisplayFor(model => model.CategoryName)
    </dd>
</dl>

WebPagesAPI/WebPagesParkingSoft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPagesParkingSoft</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,500;1,500&family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/WebPagesParkingSoft.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><h1 class="text-primary">ParkinSoft</h1></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title text-primary" id="offcanvasNavbarLabel">ParkinSoft</h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="ParkinSoft" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reserves" asp-action="Index">Reserves</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rates" asp-action="Index">Rates</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebPagesParkingSoft</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rates" asp-action="Index">Rates</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <div class="container pt-5">
        <main role="main" class="pb-3 pt-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebPagesParkingSoft - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebPagesAPI/WebPagesParkingSoft/Views/Vehicles/Create.cshtml
@model API_AppParkingSoft.DAL.Entities.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Vehiculo</h1>

<h4>Vehiculo</h4>
<hr />

a<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <partial name="../Shared/PartialView/_VehiclesCreateEdit.cshtml">

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-outline-primary" />
                <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebPagesAPI/WebPagesParkingSoft/Views/Vehicles/Delete.cshtml
@model API_AppParkingSoft.DAL.Entities.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Vehiculo</h1>

<h4>Estas seguro que deseas eliminar el vehiculo?</h4>
<hr />

a<div class="row">
    <div class="col-12">
        <partial name="../Shared/PartialView/_VehiclesDetailsDelete.cshtml">

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id"/>
            <input type="submit" value="Eliminar" class="btn btn-outline-danger" />
            <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebPagesAPI/WebPagesParkingSoft/Views/Vehicles/Edit.cshtml
@model API_AppParkingSoft.DAL.Entities.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Vehiculo</h1>

<h4>Vehiculo</h4>
<hr />

a<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id"/>

            <partial name="../Shared/PartialView/_VehiclesCreateEdit.cshtml">

                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                    <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
                </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebPagesAPI/WebPagesParkingSoft/Views/Vehicles/Index.cshtml
@model IEnumerable<API_AppParkingSoft.DAL.Entities.Vehicle>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
<a asp-action="Create" class="btn btn-outline-primary">Crear nuevo vehiculo</a>

<div class="row">
    <div class="col-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-primary text-center">Vehiculos</h3>
            </div>
        </div>

        <div class="panel-body">
            <table class="table table-hover table-responsive table-striped" id="VehiclesTable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.LicensePlate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Brand)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Model)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.LicensePlate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Brand)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Model)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Editar</a>
                                @* <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-success">Detalles</a> *@
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

@SectionWriters Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(funtion(){
            $('VehiclesTable').DataTable({
                "languaje": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [5, 25, 50, 100, 200, -1],
                    [5, 25, 50, 100, 200, "Todos"]
                ]
            })
        })
    </script>
 }